### ISSUE TITLE
15/6

### ISSUE THREAD

**Issue by TM11153431** [miloubis/Programmeerproject#1]
Milou,

Verbeterpunten voor de repo: In de readme ontbreken schetsen en potentiële issues, voeg deze nog even toe (ik weet dat je wel schetsen hebt gemaakt dus alleen een foto hiervan toevoegen is prima). Alle code staat bij jou in een map genaamd scripts, hier zou ik nog meer mapjes van maken voor de duidelijkheid. 

Qua commits heb je nu alleen nog 7 juni gemist, zorg dus wel echt dat je iedere dag commit. Eén dag niet missen is geen enorme ramp, maar zorg wel dat je vanaf nu elke dag commit.

Tim

**Comment by miloubis** [comment]
Schetsen zijn toegevoegd, ik moet alleen nog even de data in mapje data stoppen, verder heb ik alle dagen gecommit.
